resource_group_name     = "example-resources"
resource_group_location = "Central US"
storage_account_name    = "examplestorage"
storage_container_name  = "content"
blob_name               = "content.zip"
